# Triangle, pentagonal, and hexagonal numbers
# are generated by the following formulae:

# Triangle	 	       Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	   Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	       Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

def tri(n):
    return (n * (n + 1)) / 2

def pent(n):
    return (n * (3 * n - 1)) / 2

def hex(n):
    return (n * (2 * n - 1))

def get_nums(max_n, tri_list, pent_list, hex_list):
    tri_list.extend(tri(n) for n in range(len(tri_list)+1,max_n+1))
    pent_list.extend(pent(n) for n in range(len(pent_list)+1,max_n+1))
    hex_list.extend(hex(n) for n in range(len(hex_list)+1,max_n+1))
    return tri_list, pent_list, hex_list

def main():
    n = 285
    tri_list = []
    pent_list = []
    hex_list = []
    while True:
        n += 1
        tri_list, pent_list, hex_list = get_nums(n, tri_list, pent_list, hex_list)
        if tri_list[-1] in pent_list and tri_list[-1] in hex_list:
            return print((tri_list[-1]))

if __name__ == '__main__':
    main()
